name: android_trans_tool
description: "Android string res translate tool"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  chinese_font_library: ^1.0.2
  window_manager: ^0.3.7
  shared_preferences: ^2.0.6
  path: ^1.8.0
  flutter_fancy_tree_view: ^1.4.1
  provider: ^6.1.1
  xml: ^6.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
