name: android_trans_tool
description: "Android string res translate tool"
publish_to: 'none'

version: 1.0.2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  file_picker: ^10.1.9
  chinese_font_library: ^1.2.0
  window_manager: ^0.5.0
  shared_preferences: ^2.2.3
  path: ^1.9.0
  xml: ^6.5.0
  chat_gpt_sdk: ^3.0.7
#    path: ../flutter/chat_gpt_sdk
  logger: ^2.3.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
