name: android_trans_tool
description: "Android string res translate tool"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  file_picker: ^6.1.1
  chinese_font_library: ^1.0.2
  window_manager: ^0.3.7
  shared_preferences: ^2.0.6
  path: ^1.8.3
  #  flutter_fancy_tree_view: ^1.4.1
  xml: ^6.4.2
  chat_gpt_sdk:
    path: ../flutter/chat_gpt_sdk
  logger: ^2.0.2+1
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
